package com.pkpmjc.erp.sales.mapper;

import com.pkpmjc.erp.sales.entity.Contract;
import com.pkpmjc.erp.sales.entity.ContractExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int countByExample(ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int deleteByExample(ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int insert(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int insertSelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    List<Contract> selectByExampleWithBLOBs(ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    List<Contract> selectByExample(ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    Contract selectByPrimaryKey(Integer f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Contract record, @Param("example") ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Contract record, @Param("example") ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Contract record, @Param("example") ContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Contract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Contract record);
}