package com.pkpmjc.erp.sales.mapper;

import com.pkpmjc.erp.sales.entity.Customer;
import com.pkpmjc.erp.sales.entity.CustomerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    List<Customer> selectByExampleWithBLOBs(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    Customer selectByPrimaryKey(Integer f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Customer record);
}