package com.pkpmjc.erp.sales.mapper;

import com.pkpmjc.erp.sales.entity.Project;
import com.pkpmjc.erp.sales.entity.ProjectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int countByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int insertSelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    List<Project> selectByExampleWithBLOBs(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    List<Project> selectByExample(ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    Project selectByPrimaryKey(Integer f_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Project record, @Param("example") ProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Project record);
}