package com.pkpmjc.erp.sales.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ContractExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public ContractExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andF_idIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andF_idIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_idEqualTo(Integer value) {
            addCriterion("f_id =", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThan(Integer value) {
            addCriterion("f_id >", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThan(Integer value) {
            addCriterion("f_id <", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idIn(List<Integer> values) {
            addCriterion("f_id in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_noIsNull() {
            addCriterion("f_contract_no is null");
            return (Criteria) this;
        }

        public Criteria andF_contract_noIsNotNull() {
            addCriterion("f_contract_no is not null");
            return (Criteria) this;
        }

        public Criteria andF_contract_noEqualTo(String value) {
            addCriterion("f_contract_no =", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noNotEqualTo(String value) {
            addCriterion("f_contract_no <>", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noGreaterThan(String value) {
            addCriterion("f_contract_no >", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noGreaterThanOrEqualTo(String value) {
            addCriterion("f_contract_no >=", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noLessThan(String value) {
            addCriterion("f_contract_no <", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noLessThanOrEqualTo(String value) {
            addCriterion("f_contract_no <=", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noLike(String value) {
            addCriterion("f_contract_no like", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noNotLike(String value) {
            addCriterion("f_contract_no not like", value, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noIn(List<String> values) {
            addCriterion("f_contract_no in", values, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noNotIn(List<String> values) {
            addCriterion("f_contract_no not in", values, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noBetween(String value1, String value2) {
            addCriterion("f_contract_no between", value1, value2, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_noNotBetween(String value1, String value2) {
            addCriterion("f_contract_no not between", value1, value2, "f_contract_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameIsNull() {
            addCriterion("f_contract_name is null");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameIsNotNull() {
            addCriterion("f_contract_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameEqualTo(String value) {
            addCriterion("f_contract_name =", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameNotEqualTo(String value) {
            addCriterion("f_contract_name <>", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameGreaterThan(String value) {
            addCriterion("f_contract_name >", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_contract_name >=", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameLessThan(String value) {
            addCriterion("f_contract_name <", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameLessThanOrEqualTo(String value) {
            addCriterion("f_contract_name <=", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameLike(String value) {
            addCriterion("f_contract_name like", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameNotLike(String value) {
            addCriterion("f_contract_name not like", value, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameIn(List<String> values) {
            addCriterion("f_contract_name in", values, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameNotIn(List<String> values) {
            addCriterion("f_contract_name not in", values, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameBetween(String value1, String value2) {
            addCriterion("f_contract_name between", value1, value2, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_nameNotBetween(String value1, String value2) {
            addCriterion("f_contract_name not between", value1, value2, "f_contract_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeIsNull() {
            addCriterion("f_contract_type is null");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeIsNotNull() {
            addCriterion("f_contract_type is not null");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeEqualTo(Integer value) {
            addCriterion("f_contract_type =", value, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeNotEqualTo(Integer value) {
            addCriterion("f_contract_type <>", value, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeGreaterThan(Integer value) {
            addCriterion("f_contract_type >", value, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_contract_type >=", value, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeLessThan(Integer value) {
            addCriterion("f_contract_type <", value, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeLessThanOrEqualTo(Integer value) {
            addCriterion("f_contract_type <=", value, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeIn(List<Integer> values) {
            addCriterion("f_contract_type in", values, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeNotIn(List<Integer> values) {
            addCriterion("f_contract_type not in", values, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeBetween(Integer value1, Integer value2) {
            addCriterion("f_contract_type between", value1, value2, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_contract_typeNotBetween(Integer value1, Integer value2) {
            addCriterion("f_contract_type not between", value1, value2, "f_contract_type");
            return (Criteria) this;
        }

        public Criteria andF_customer_idIsNull() {
            addCriterion("f_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andF_customer_idIsNotNull() {
            addCriterion("f_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_customer_idEqualTo(Integer value) {
            addCriterion("f_customer_id =", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idNotEqualTo(Integer value) {
            addCriterion("f_customer_id <>", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idGreaterThan(Integer value) {
            addCriterion("f_customer_id >", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_customer_id >=", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idLessThan(Integer value) {
            addCriterion("f_customer_id <", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_customer_id <=", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idIn(List<Integer> values) {
            addCriterion("f_customer_id in", values, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idNotIn(List<Integer> values) {
            addCriterion("f_customer_id not in", values, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idBetween(Integer value1, Integer value2) {
            addCriterion("f_customer_id between", value1, value2, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_customer_id not between", value1, value2, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_total_numIsNull() {
            addCriterion("f_total_num is null");
            return (Criteria) this;
        }

        public Criteria andF_total_numIsNotNull() {
            addCriterion("f_total_num is not null");
            return (Criteria) this;
        }

        public Criteria andF_total_numEqualTo(Double value) {
            addCriterion("f_total_num =", value, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numNotEqualTo(Double value) {
            addCriterion("f_total_num <>", value, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numGreaterThan(Double value) {
            addCriterion("f_total_num >", value, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numGreaterThanOrEqualTo(Double value) {
            addCriterion("f_total_num >=", value, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numLessThan(Double value) {
            addCriterion("f_total_num <", value, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numLessThanOrEqualTo(Double value) {
            addCriterion("f_total_num <=", value, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numIn(List<Double> values) {
            addCriterion("f_total_num in", values, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numNotIn(List<Double> values) {
            addCriterion("f_total_num not in", values, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numBetween(Double value1, Double value2) {
            addCriterion("f_total_num between", value1, value2, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_total_numNotBetween(Double value1, Double value2) {
            addCriterion("f_total_num not between", value1, value2, "f_total_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numIsNull() {
            addCriterion("f_upper_num is null");
            return (Criteria) this;
        }

        public Criteria andF_upper_numIsNotNull() {
            addCriterion("f_upper_num is not null");
            return (Criteria) this;
        }

        public Criteria andF_upper_numEqualTo(Double value) {
            addCriterion("f_upper_num =", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numNotEqualTo(Double value) {
            addCriterion("f_upper_num <>", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numGreaterThan(Double value) {
            addCriterion("f_upper_num >", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numGreaterThanOrEqualTo(Double value) {
            addCriterion("f_upper_num >=", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numLessThan(Double value) {
            addCriterion("f_upper_num <", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numLessThanOrEqualTo(Double value) {
            addCriterion("f_upper_num <=", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numIn(List<Double> values) {
            addCriterion("f_upper_num in", values, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numNotIn(List<Double> values) {
            addCriterion("f_upper_num not in", values, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numBetween(Double value1, Double value2) {
            addCriterion("f_upper_num between", value1, value2, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numNotBetween(Double value1, Double value2) {
            addCriterion("f_upper_num not between", value1, value2, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_signerIsNull() {
            addCriterion("f_signer is null");
            return (Criteria) this;
        }

        public Criteria andF_signerIsNotNull() {
            addCriterion("f_signer is not null");
            return (Criteria) this;
        }

        public Criteria andF_signerEqualTo(Integer value) {
            addCriterion("f_signer =", value, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerNotEqualTo(Integer value) {
            addCriterion("f_signer <>", value, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerGreaterThan(Integer value) {
            addCriterion("f_signer >", value, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_signer >=", value, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerLessThan(Integer value) {
            addCriterion("f_signer <", value, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerLessThanOrEqualTo(Integer value) {
            addCriterion("f_signer <=", value, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerIn(List<Integer> values) {
            addCriterion("f_signer in", values, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerNotIn(List<Integer> values) {
            addCriterion("f_signer not in", values, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerBetween(Integer value1, Integer value2) {
            addCriterion("f_signer between", value1, value2, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_signerNotBetween(Integer value1, Integer value2) {
            addCriterion("f_signer not between", value1, value2, "f_signer");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateIsNull() {
            addCriterion("f_sign_date is null");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateIsNotNull() {
            addCriterion("f_sign_date is not null");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateEqualTo(Date value) {
            addCriterionForJDBCDate("f_sign_date =", value, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateNotEqualTo(Date value) {
            addCriterionForJDBCDate("f_sign_date <>", value, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateGreaterThan(Date value) {
            addCriterionForJDBCDate("f_sign_date >", value, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("f_sign_date >=", value, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateLessThan(Date value) {
            addCriterionForJDBCDate("f_sign_date <", value, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("f_sign_date <=", value, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateIn(List<Date> values) {
            addCriterionForJDBCDate("f_sign_date in", values, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateNotIn(List<Date> values) {
            addCriterionForJDBCDate("f_sign_date not in", values, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("f_sign_date between", value1, value2, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_sign_dateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("f_sign_date not between", value1, value2, "f_sign_date");
            return (Criteria) this;
        }

        public Criteria andF_linkerIsNull() {
            addCriterion("f_linker is null");
            return (Criteria) this;
        }

        public Criteria andF_linkerIsNotNull() {
            addCriterion("f_linker is not null");
            return (Criteria) this;
        }

        public Criteria andF_linkerEqualTo(String value) {
            addCriterion("f_linker =", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotEqualTo(String value) {
            addCriterion("f_linker <>", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerGreaterThan(String value) {
            addCriterion("f_linker >", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerGreaterThanOrEqualTo(String value) {
            addCriterion("f_linker >=", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLessThan(String value) {
            addCriterion("f_linker <", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLessThanOrEqualTo(String value) {
            addCriterion("f_linker <=", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLike(String value) {
            addCriterion("f_linker like", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotLike(String value) {
            addCriterion("f_linker not like", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerIn(List<String> values) {
            addCriterion("f_linker in", values, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotIn(List<String> values) {
            addCriterion("f_linker not in", values, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerBetween(String value1, String value2) {
            addCriterion("f_linker between", value1, value2, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotBetween(String value1, String value2) {
            addCriterion("f_linker not between", value1, value2, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneIsNull() {
            addCriterion("f_link_phone is null");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneIsNotNull() {
            addCriterion("f_link_phone is not null");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneEqualTo(String value) {
            addCriterion("f_link_phone =", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotEqualTo(String value) {
            addCriterion("f_link_phone <>", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneGreaterThan(String value) {
            addCriterion("f_link_phone >", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_link_phone >=", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneLessThan(String value) {
            addCriterion("f_link_phone <", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneLessThanOrEqualTo(String value) {
            addCriterion("f_link_phone <=", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneLike(String value) {
            addCriterion("f_link_phone like", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotLike(String value) {
            addCriterion("f_link_phone not like", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneIn(List<String> values) {
            addCriterion("f_link_phone in", values, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotIn(List<String> values) {
            addCriterion("f_link_phone not in", values, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneBetween(String value1, String value2) {
            addCriterion("f_link_phone between", value1, value2, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotBetween(String value1, String value2) {
            addCriterion("f_link_phone not between", value1, value2, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoIsNull() {
            addCriterion("f_audit_memo is null");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoIsNotNull() {
            addCriterion("f_audit_memo is not null");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoEqualTo(String value) {
            addCriterion("f_audit_memo =", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoNotEqualTo(String value) {
            addCriterion("f_audit_memo <>", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoGreaterThan(String value) {
            addCriterion("f_audit_memo >", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoGreaterThanOrEqualTo(String value) {
            addCriterion("f_audit_memo >=", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoLessThan(String value) {
            addCriterion("f_audit_memo <", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoLessThanOrEqualTo(String value) {
            addCriterion("f_audit_memo <=", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoLike(String value) {
            addCriterion("f_audit_memo like", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoNotLike(String value) {
            addCriterion("f_audit_memo not like", value, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoIn(List<String> values) {
            addCriterion("f_audit_memo in", values, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoNotIn(List<String> values) {
            addCriterion("f_audit_memo not in", values, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoBetween(String value1, String value2) {
            addCriterion("f_audit_memo between", value1, value2, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_audit_memoNotBetween(String value1, String value2) {
            addCriterion("f_audit_memo not between", value1, value2, "f_audit_memo");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andF_statusEqualTo(Integer value) {
            addCriterion("f_status =", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotEqualTo(Integer value) {
            addCriterion("f_status <>", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThan(Integer value) {
            addCriterion("f_status >", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_status >=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThan(Integer value) {
            addCriterion("f_status <", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThanOrEqualTo(Integer value) {
            addCriterion("f_status <=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusIn(List<Integer> values) {
            addCriterion("f_status in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotIn(List<Integer> values) {
            addCriterion("f_status not in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusBetween(Integer value1, Integer value2) {
            addCriterion("f_status between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("f_status not between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_file_nameIsNull() {
            addCriterion("f_file_name is null");
            return (Criteria) this;
        }

        public Criteria andF_file_nameIsNotNull() {
            addCriterion("f_file_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_file_nameEqualTo(String value) {
            addCriterion("f_file_name =", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameNotEqualTo(String value) {
            addCriterion("f_file_name <>", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameGreaterThan(String value) {
            addCriterion("f_file_name >", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_file_name >=", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameLessThan(String value) {
            addCriterion("f_file_name <", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameLessThanOrEqualTo(String value) {
            addCriterion("f_file_name <=", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameLike(String value) {
            addCriterion("f_file_name like", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameNotLike(String value) {
            addCriterion("f_file_name not like", value, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameIn(List<String> values) {
            addCriterion("f_file_name in", values, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameNotIn(List<String> values) {
            addCriterion("f_file_name not in", values, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameBetween(String value1, String value2) {
            addCriterion("f_file_name between", value1, value2, "f_file_name");
            return (Criteria) this;
        }

        public Criteria andF_file_nameNotBetween(String value1, String value2) {
            addCriterion("f_file_name not between", value1, value2, "f_file_name");
            return (Criteria) this;
        }
    }

    /**
    t_sales_contract
     *
     * @mbggenerated do_not_delete_during_merge
     *
     * @mbggenerated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sales_contract
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}