package com.pkpmjc.erp.sales.entity;

import java.util.ArrayList;
import java.util.List;

public class CustomerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public CustomerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_idIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andF_idIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_idEqualTo(Integer value) {
            addCriterion("f_id =", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThan(Integer value) {
            addCriterion("f_id >", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThan(Integer value) {
            addCriterion("f_id <", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idIn(List<Integer> values) {
            addCriterion("f_id in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_noIsNull() {
            addCriterion("f_customer_no is null");
            return (Criteria) this;
        }

        public Criteria andF_customer_noIsNotNull() {
            addCriterion("f_customer_no is not null");
            return (Criteria) this;
        }

        public Criteria andF_customer_noEqualTo(String value) {
            addCriterion("f_customer_no =", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noNotEqualTo(String value) {
            addCriterion("f_customer_no <>", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noGreaterThan(String value) {
            addCriterion("f_customer_no >", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noGreaterThanOrEqualTo(String value) {
            addCriterion("f_customer_no >=", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noLessThan(String value) {
            addCriterion("f_customer_no <", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noLessThanOrEqualTo(String value) {
            addCriterion("f_customer_no <=", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noLike(String value) {
            addCriterion("f_customer_no like", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noNotLike(String value) {
            addCriterion("f_customer_no not like", value, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noIn(List<String> values) {
            addCriterion("f_customer_no in", values, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noNotIn(List<String> values) {
            addCriterion("f_customer_no not in", values, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noBetween(String value1, String value2) {
            addCriterion("f_customer_no between", value1, value2, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_noNotBetween(String value1, String value2) {
            addCriterion("f_customer_no not between", value1, value2, "f_customer_no");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameIsNull() {
            addCriterion("f_customer_name is null");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameIsNotNull() {
            addCriterion("f_customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameEqualTo(String value) {
            addCriterion("f_customer_name =", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameNotEqualTo(String value) {
            addCriterion("f_customer_name <>", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameGreaterThan(String value) {
            addCriterion("f_customer_name >", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_customer_name >=", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameLessThan(String value) {
            addCriterion("f_customer_name <", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameLessThanOrEqualTo(String value) {
            addCriterion("f_customer_name <=", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameLike(String value) {
            addCriterion("f_customer_name like", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameNotLike(String value) {
            addCriterion("f_customer_name not like", value, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameIn(List<String> values) {
            addCriterion("f_customer_name in", values, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameNotIn(List<String> values) {
            addCriterion("f_customer_name not in", values, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameBetween(String value1, String value2) {
            addCriterion("f_customer_name between", value1, value2, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_customer_nameNotBetween(String value1, String value2) {
            addCriterion("f_customer_name not between", value1, value2, "f_customer_name");
            return (Criteria) this;
        }

        public Criteria andF_linkerIsNull() {
            addCriterion("f_linker is null");
            return (Criteria) this;
        }

        public Criteria andF_linkerIsNotNull() {
            addCriterion("f_linker is not null");
            return (Criteria) this;
        }

        public Criteria andF_linkerEqualTo(String value) {
            addCriterion("f_linker =", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotEqualTo(String value) {
            addCriterion("f_linker <>", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerGreaterThan(String value) {
            addCriterion("f_linker >", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerGreaterThanOrEqualTo(String value) {
            addCriterion("f_linker >=", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLessThan(String value) {
            addCriterion("f_linker <", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLessThanOrEqualTo(String value) {
            addCriterion("f_linker <=", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLike(String value) {
            addCriterion("f_linker like", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotLike(String value) {
            addCriterion("f_linker not like", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerIn(List<String> values) {
            addCriterion("f_linker in", values, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotIn(List<String> values) {
            addCriterion("f_linker not in", values, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerBetween(String value1, String value2) {
            addCriterion("f_linker between", value1, value2, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotBetween(String value1, String value2) {
            addCriterion("f_linker not between", value1, value2, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_telIsNull() {
            addCriterion("f_tel is null");
            return (Criteria) this;
        }

        public Criteria andF_telIsNotNull() {
            addCriterion("f_tel is not null");
            return (Criteria) this;
        }

        public Criteria andF_telEqualTo(String value) {
            addCriterion("f_tel =", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telNotEqualTo(String value) {
            addCriterion("f_tel <>", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telGreaterThan(String value) {
            addCriterion("f_tel >", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telGreaterThanOrEqualTo(String value) {
            addCriterion("f_tel >=", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telLessThan(String value) {
            addCriterion("f_tel <", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telLessThanOrEqualTo(String value) {
            addCriterion("f_tel <=", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telLike(String value) {
            addCriterion("f_tel like", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telNotLike(String value) {
            addCriterion("f_tel not like", value, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telIn(List<String> values) {
            addCriterion("f_tel in", values, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telNotIn(List<String> values) {
            addCriterion("f_tel not in", values, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telBetween(String value1, String value2) {
            addCriterion("f_tel between", value1, value2, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_telNotBetween(String value1, String value2) {
            addCriterion("f_tel not between", value1, value2, "f_tel");
            return (Criteria) this;
        }

        public Criteria andF_faxIsNull() {
            addCriterion("f_fax is null");
            return (Criteria) this;
        }

        public Criteria andF_faxIsNotNull() {
            addCriterion("f_fax is not null");
            return (Criteria) this;
        }

        public Criteria andF_faxEqualTo(String value) {
            addCriterion("f_fax =", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxNotEqualTo(String value) {
            addCriterion("f_fax <>", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxGreaterThan(String value) {
            addCriterion("f_fax >", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxGreaterThanOrEqualTo(String value) {
            addCriterion("f_fax >=", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxLessThan(String value) {
            addCriterion("f_fax <", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxLessThanOrEqualTo(String value) {
            addCriterion("f_fax <=", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxLike(String value) {
            addCriterion("f_fax like", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxNotLike(String value) {
            addCriterion("f_fax not like", value, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxIn(List<String> values) {
            addCriterion("f_fax in", values, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxNotIn(List<String> values) {
            addCriterion("f_fax not in", values, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxBetween(String value1, String value2) {
            addCriterion("f_fax between", value1, value2, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_faxNotBetween(String value1, String value2) {
            addCriterion("f_fax not between", value1, value2, "f_fax");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andF_statusEqualTo(Integer value) {
            addCriterion("f_status =", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotEqualTo(Integer value) {
            addCriterion("f_status <>", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThan(Integer value) {
            addCriterion("f_status >", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_status >=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThan(Integer value) {
            addCriterion("f_status <", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThanOrEqualTo(Integer value) {
            addCriterion("f_status <=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusIn(List<Integer> values) {
            addCriterion("f_status in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotIn(List<Integer> values) {
            addCriterion("f_status not in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusBetween(Integer value1, Integer value2) {
            addCriterion("f_status between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("f_status not between", value1, value2, "f_status");
            return (Criteria) this;
        }
    }

    /**
    t_sales_customer
     *
     * @mbggenerated do_not_delete_during_merge
     *
     * @mbggenerated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sales_customer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}