package com.pkpmjc.erp.sales.entity;

import java.util.ArrayList;
import java.util.List;

public class ProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public ProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andF_idIsNull() {
            addCriterion("f_id is null");
            return (Criteria) this;
        }

        public Criteria andF_idIsNotNull() {
            addCriterion("f_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_idEqualTo(Integer value) {
            addCriterion("f_id =", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotEqualTo(Integer value) {
            addCriterion("f_id <>", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThan(Integer value) {
            addCriterion("f_id >", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_id >=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThan(Integer value) {
            addCriterion("f_id <", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_id <=", value, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idIn(List<Integer> values) {
            addCriterion("f_id in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotIn(List<Integer> values) {
            addCriterion("f_id not in", values, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idBetween(Integer value1, Integer value2) {
            addCriterion("f_id between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_id not between", value1, value2, "f_id");
            return (Criteria) this;
        }

        public Criteria andF_project_noIsNull() {
            addCriterion("f_project_no is null");
            return (Criteria) this;
        }

        public Criteria andF_project_noIsNotNull() {
            addCriterion("f_project_no is not null");
            return (Criteria) this;
        }

        public Criteria andF_project_noEqualTo(String value) {
            addCriterion("f_project_no =", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noNotEqualTo(String value) {
            addCriterion("f_project_no <>", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noGreaterThan(String value) {
            addCriterion("f_project_no >", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noGreaterThanOrEqualTo(String value) {
            addCriterion("f_project_no >=", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noLessThan(String value) {
            addCriterion("f_project_no <", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noLessThanOrEqualTo(String value) {
            addCriterion("f_project_no <=", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noLike(String value) {
            addCriterion("f_project_no like", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noNotLike(String value) {
            addCriterion("f_project_no not like", value, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noIn(List<String> values) {
            addCriterion("f_project_no in", values, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noNotIn(List<String> values) {
            addCriterion("f_project_no not in", values, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noBetween(String value1, String value2) {
            addCriterion("f_project_no between", value1, value2, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_noNotBetween(String value1, String value2) {
            addCriterion("f_project_no not between", value1, value2, "f_project_no");
            return (Criteria) this;
        }

        public Criteria andF_project_nameIsNull() {
            addCriterion("f_project_name is null");
            return (Criteria) this;
        }

        public Criteria andF_project_nameIsNotNull() {
            addCriterion("f_project_name is not null");
            return (Criteria) this;
        }

        public Criteria andF_project_nameEqualTo(String value) {
            addCriterion("f_project_name =", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameNotEqualTo(String value) {
            addCriterion("f_project_name <>", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameGreaterThan(String value) {
            addCriterion("f_project_name >", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameGreaterThanOrEqualTo(String value) {
            addCriterion("f_project_name >=", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameLessThan(String value) {
            addCriterion("f_project_name <", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameLessThanOrEqualTo(String value) {
            addCriterion("f_project_name <=", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameLike(String value) {
            addCriterion("f_project_name like", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameNotLike(String value) {
            addCriterion("f_project_name not like", value, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameIn(List<String> values) {
            addCriterion("f_project_name in", values, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameNotIn(List<String> values) {
            addCriterion("f_project_name not in", values, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameBetween(String value1, String value2) {
            addCriterion("f_project_name between", value1, value2, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_project_nameNotBetween(String value1, String value2) {
            addCriterion("f_project_name not between", value1, value2, "f_project_name");
            return (Criteria) this;
        }

        public Criteria andF_contract_idIsNull() {
            addCriterion("f_contract_id is null");
            return (Criteria) this;
        }

        public Criteria andF_contract_idIsNotNull() {
            addCriterion("f_contract_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_contract_idEqualTo(Integer value) {
            addCriterion("f_contract_id =", value, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idNotEqualTo(Integer value) {
            addCriterion("f_contract_id <>", value, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idGreaterThan(Integer value) {
            addCriterion("f_contract_id >", value, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_contract_id >=", value, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idLessThan(Integer value) {
            addCriterion("f_contract_id <", value, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_contract_id <=", value, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idIn(List<Integer> values) {
            addCriterion("f_contract_id in", values, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idNotIn(List<Integer> values) {
            addCriterion("f_contract_id not in", values, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idBetween(Integer value1, Integer value2) {
            addCriterion("f_contract_id between", value1, value2, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_contract_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_contract_id not between", value1, value2, "f_contract_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idIsNull() {
            addCriterion("f_customer_id is null");
            return (Criteria) this;
        }

        public Criteria andF_customer_idIsNotNull() {
            addCriterion("f_customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andF_customer_idEqualTo(Integer value) {
            addCriterion("f_customer_id =", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idNotEqualTo(Integer value) {
            addCriterion("f_customer_id <>", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idGreaterThan(Integer value) {
            addCriterion("f_customer_id >", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_customer_id >=", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idLessThan(Integer value) {
            addCriterion("f_customer_id <", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idLessThanOrEqualTo(Integer value) {
            addCriterion("f_customer_id <=", value, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idIn(List<Integer> values) {
            addCriterion("f_customer_id in", values, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idNotIn(List<Integer> values) {
            addCriterion("f_customer_id not in", values, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idBetween(Integer value1, Integer value2) {
            addCriterion("f_customer_id between", value1, value2, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_customer_idNotBetween(Integer value1, Integer value2) {
            addCriterion("f_customer_id not between", value1, value2, "f_customer_id");
            return (Criteria) this;
        }

        public Criteria andF_build_companyIsNull() {
            addCriterion("f_build_company is null");
            return (Criteria) this;
        }

        public Criteria andF_build_companyIsNotNull() {
            addCriterion("f_build_company is not null");
            return (Criteria) this;
        }

        public Criteria andF_build_companyEqualTo(String value) {
            addCriterion("f_build_company =", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyNotEqualTo(String value) {
            addCriterion("f_build_company <>", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyGreaterThan(String value) {
            addCriterion("f_build_company >", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyGreaterThanOrEqualTo(String value) {
            addCriterion("f_build_company >=", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyLessThan(String value) {
            addCriterion("f_build_company <", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyLessThanOrEqualTo(String value) {
            addCriterion("f_build_company <=", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyLike(String value) {
            addCriterion("f_build_company like", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyNotLike(String value) {
            addCriterion("f_build_company not like", value, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyIn(List<String> values) {
            addCriterion("f_build_company in", values, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyNotIn(List<String> values) {
            addCriterion("f_build_company not in", values, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyBetween(String value1, String value2) {
            addCriterion("f_build_company between", value1, value2, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_build_companyNotBetween(String value1, String value2) {
            addCriterion("f_build_company not between", value1, value2, "f_build_company");
            return (Criteria) this;
        }

        public Criteria andF_upper_numIsNull() {
            addCriterion("f_upper_num is null");
            return (Criteria) this;
        }

        public Criteria andF_upper_numIsNotNull() {
            addCriterion("f_upper_num is not null");
            return (Criteria) this;
        }

        public Criteria andF_upper_numEqualTo(Double value) {
            addCriterion("f_upper_num =", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numNotEqualTo(Double value) {
            addCriterion("f_upper_num <>", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numGreaterThan(Double value) {
            addCriterion("f_upper_num >", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numGreaterThanOrEqualTo(Double value) {
            addCriterion("f_upper_num >=", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numLessThan(Double value) {
            addCriterion("f_upper_num <", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numLessThanOrEqualTo(Double value) {
            addCriterion("f_upper_num <=", value, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numIn(List<Double> values) {
            addCriterion("f_upper_num in", values, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numNotIn(List<Double> values) {
            addCriterion("f_upper_num not in", values, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numBetween(Double value1, Double value2) {
            addCriterion("f_upper_num between", value1, value2, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_upper_numNotBetween(Double value1, Double value2) {
            addCriterion("f_upper_num not between", value1, value2, "f_upper_num");
            return (Criteria) this;
        }

        public Criteria andF_linkerIsNull() {
            addCriterion("f_linker is null");
            return (Criteria) this;
        }

        public Criteria andF_linkerIsNotNull() {
            addCriterion("f_linker is not null");
            return (Criteria) this;
        }

        public Criteria andF_linkerEqualTo(String value) {
            addCriterion("f_linker =", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotEqualTo(String value) {
            addCriterion("f_linker <>", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerGreaterThan(String value) {
            addCriterion("f_linker >", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerGreaterThanOrEqualTo(String value) {
            addCriterion("f_linker >=", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLessThan(String value) {
            addCriterion("f_linker <", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLessThanOrEqualTo(String value) {
            addCriterion("f_linker <=", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerLike(String value) {
            addCriterion("f_linker like", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotLike(String value) {
            addCriterion("f_linker not like", value, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerIn(List<String> values) {
            addCriterion("f_linker in", values, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotIn(List<String> values) {
            addCriterion("f_linker not in", values, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerBetween(String value1, String value2) {
            addCriterion("f_linker between", value1, value2, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_linkerNotBetween(String value1, String value2) {
            addCriterion("f_linker not between", value1, value2, "f_linker");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneIsNull() {
            addCriterion("f_link_phone is null");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneIsNotNull() {
            addCriterion("f_link_phone is not null");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneEqualTo(String value) {
            addCriterion("f_link_phone =", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotEqualTo(String value) {
            addCriterion("f_link_phone <>", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneGreaterThan(String value) {
            addCriterion("f_link_phone >", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneGreaterThanOrEqualTo(String value) {
            addCriterion("f_link_phone >=", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneLessThan(String value) {
            addCriterion("f_link_phone <", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneLessThanOrEqualTo(String value) {
            addCriterion("f_link_phone <=", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneLike(String value) {
            addCriterion("f_link_phone like", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotLike(String value) {
            addCriterion("f_link_phone not like", value, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneIn(List<String> values) {
            addCriterion("f_link_phone in", values, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotIn(List<String> values) {
            addCriterion("f_link_phone not in", values, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneBetween(String value1, String value2) {
            addCriterion("f_link_phone between", value1, value2, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_link_phoneNotBetween(String value1, String value2) {
            addCriterion("f_link_phone not between", value1, value2, "f_link_phone");
            return (Criteria) this;
        }

        public Criteria andF_addressIsNull() {
            addCriterion("f_address is null");
            return (Criteria) this;
        }

        public Criteria andF_addressIsNotNull() {
            addCriterion("f_address is not null");
            return (Criteria) this;
        }

        public Criteria andF_addressEqualTo(String value) {
            addCriterion("f_address =", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotEqualTo(String value) {
            addCriterion("f_address <>", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressGreaterThan(String value) {
            addCriterion("f_address >", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressGreaterThanOrEqualTo(String value) {
            addCriterion("f_address >=", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressLessThan(String value) {
            addCriterion("f_address <", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressLessThanOrEqualTo(String value) {
            addCriterion("f_address <=", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressLike(String value) {
            addCriterion("f_address like", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotLike(String value) {
            addCriterion("f_address not like", value, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressIn(List<String> values) {
            addCriterion("f_address in", values, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotIn(List<String> values) {
            addCriterion("f_address not in", values, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressBetween(String value1, String value2) {
            addCriterion("f_address between", value1, value2, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_addressNotBetween(String value1, String value2) {
            addCriterion("f_address not between", value1, value2, "f_address");
            return (Criteria) this;
        }

        public Criteria andF_distanceIsNull() {
            addCriterion("f_distance is null");
            return (Criteria) this;
        }

        public Criteria andF_distanceIsNotNull() {
            addCriterion("f_distance is not null");
            return (Criteria) this;
        }

        public Criteria andF_distanceEqualTo(Double value) {
            addCriterion("f_distance =", value, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceNotEqualTo(Double value) {
            addCriterion("f_distance <>", value, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceGreaterThan(Double value) {
            addCriterion("f_distance >", value, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceGreaterThanOrEqualTo(Double value) {
            addCriterion("f_distance >=", value, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceLessThan(Double value) {
            addCriterion("f_distance <", value, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceLessThanOrEqualTo(Double value) {
            addCriterion("f_distance <=", value, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceIn(List<Double> values) {
            addCriterion("f_distance in", values, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceNotIn(List<Double> values) {
            addCriterion("f_distance not in", values, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceBetween(Double value1, Double value2) {
            addCriterion("f_distance between", value1, value2, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_distanceNotBetween(Double value1, Double value2) {
            addCriterion("f_distance not between", value1, value2, "f_distance");
            return (Criteria) this;
        }

        public Criteria andF_salesmanIsNull() {
            addCriterion("f_salesman is null");
            return (Criteria) this;
        }

        public Criteria andF_salesmanIsNotNull() {
            addCriterion("f_salesman is not null");
            return (Criteria) this;
        }

        public Criteria andF_salesmanEqualTo(Integer value) {
            addCriterion("f_salesman =", value, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanNotEqualTo(Integer value) {
            addCriterion("f_salesman <>", value, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanGreaterThan(Integer value) {
            addCriterion("f_salesman >", value, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_salesman >=", value, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanLessThan(Integer value) {
            addCriterion("f_salesman <", value, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanLessThanOrEqualTo(Integer value) {
            addCriterion("f_salesman <=", value, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanIn(List<Integer> values) {
            addCriterion("f_salesman in", values, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanNotIn(List<Integer> values) {
            addCriterion("f_salesman not in", values, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanBetween(Integer value1, Integer value2) {
            addCriterion("f_salesman between", value1, value2, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_salesmanNotBetween(Integer value1, Integer value2) {
            addCriterion("f_salesman not between", value1, value2, "f_salesman");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noIsNull() {
            addCriterion("f_contract_record_no is null");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noIsNotNull() {
            addCriterion("f_contract_record_no is not null");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noEqualTo(String value) {
            addCriterion("f_contract_record_no =", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noNotEqualTo(String value) {
            addCriterion("f_contract_record_no <>", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noGreaterThan(String value) {
            addCriterion("f_contract_record_no >", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noGreaterThanOrEqualTo(String value) {
            addCriterion("f_contract_record_no >=", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noLessThan(String value) {
            addCriterion("f_contract_record_no <", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noLessThanOrEqualTo(String value) {
            addCriterion("f_contract_record_no <=", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noLike(String value) {
            addCriterion("f_contract_record_no like", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noNotLike(String value) {
            addCriterion("f_contract_record_no not like", value, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noIn(List<String> values) {
            addCriterion("f_contract_record_no in", values, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noNotIn(List<String> values) {
            addCriterion("f_contract_record_no not in", values, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noBetween(String value1, String value2) {
            addCriterion("f_contract_record_no between", value1, value2, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_contract_record_noNotBetween(String value1, String value2) {
            addCriterion("f_contract_record_no not between", value1, value2, "f_contract_record_no");
            return (Criteria) this;
        }

        public Criteria andF_orderIsNull() {
            addCriterion("f_order is null");
            return (Criteria) this;
        }

        public Criteria andF_orderIsNotNull() {
            addCriterion("f_order is not null");
            return (Criteria) this;
        }

        public Criteria andF_orderEqualTo(Integer value) {
            addCriterion("f_order =", value, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderNotEqualTo(Integer value) {
            addCriterion("f_order <>", value, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderGreaterThan(Integer value) {
            addCriterion("f_order >", value, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_order >=", value, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderLessThan(Integer value) {
            addCriterion("f_order <", value, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderLessThanOrEqualTo(Integer value) {
            addCriterion("f_order <=", value, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderIn(List<Integer> values) {
            addCriterion("f_order in", values, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderNotIn(List<Integer> values) {
            addCriterion("f_order not in", values, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderBetween(Integer value1, Integer value2) {
            addCriterion("f_order between", value1, value2, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_orderNotBetween(Integer value1, Integer value2) {
            addCriterion("f_order not between", value1, value2, "f_order");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNull() {
            addCriterion("f_status is null");
            return (Criteria) this;
        }

        public Criteria andF_statusIsNotNull() {
            addCriterion("f_status is not null");
            return (Criteria) this;
        }

        public Criteria andF_statusEqualTo(Integer value) {
            addCriterion("f_status =", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotEqualTo(Integer value) {
            addCriterion("f_status <>", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThan(Integer value) {
            addCriterion("f_status >", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusGreaterThanOrEqualTo(Integer value) {
            addCriterion("f_status >=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThan(Integer value) {
            addCriterion("f_status <", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusLessThanOrEqualTo(Integer value) {
            addCriterion("f_status <=", value, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusIn(List<Integer> values) {
            addCriterion("f_status in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotIn(List<Integer> values) {
            addCriterion("f_status not in", values, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusBetween(Integer value1, Integer value2) {
            addCriterion("f_status between", value1, value2, "f_status");
            return (Criteria) this;
        }

        public Criteria andF_statusNotBetween(Integer value1, Integer value2) {
            addCriterion("f_status not between", value1, value2, "f_status");
            return (Criteria) this;
        }
    }

    /**
    t_sales_project
     *
     * @mbggenerated do_not_delete_during_merge
     *
     * @mbggenerated
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_sales_project
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}